# version format
version: 3.2.{build}.0
install:

- cmd: >-
    powershell -Command "Invoke-WebRequest https://github.com/DLR-SC/tixi/releases/download/v3.0.3/TIXI-3.0.3-win32.zip -OutFile c:\projects\cpacs-yh7xj\TIXI-3.0.3-win32.zip"
    7z x -y c:\projects\cpacs-yh7xj\TIXI-3.0.3-win32.zip -oc:\projects\cpacs-yh7xj\tools
    SET PATH=c:\projects\cpacs-yh7xj\tools\TIXI-3.0.3-win32\bin;%PATH%
    SET PYTHONPATH=c:\projects\cpacs-yh7xj\tools\TIXI-3.0.3-win32\share\tixi\python;%PYTHONPATH%
    python -V
build_script:
- cmd: >-
    echo "running schema validation..."
    python tests/test.py
test: off